require("langmapper").setup({})
local map = require("langmapper").map

map("n", "<Leader>e", "<Cmd>Neotree toggle<Cr>")
map("n", "<Leader>ff", "<Cmd>Telescope find_files<Cr>")
map("n", "<Leader>fr", "<Cmd>Telescope oldfiles<Cr>")
map("n", "<Leader>fb", "<Cmd>Telescope buffers<Cr>")
map("n", "<Leader>cs", "<Cmd>Telescope colorscheme<Cr>")
map("n", "<leader>cl", "<Cmd>CommentToggle<CR>")
map("n", "<leader>c", "<Cmd>CommentToggle<CR>")
map("n", "<leader>u", "<Cmd>Telescope undo<CR>")
map("n", "<leader>gb", "<Cmd>Telescope git_branches<CR>")
map("n", "<leader>gс", "<Cmd>Telescope git_commits<CR>")
map("n", "<leader>gf", "<Cmd>Telescope git_files<CR>")
map("n", "<leader>bd", "<Cmd>bdelete<CR>")
map("n", "gg", "<cmd>gg")
map("n", "G", "G")
map("n", "yy", "yy_")
map("n", "dd", "dd_")
map("n", "/", "/")
map("n", "?", "?")

map("v", "e", "e")
map("v", "b", "b")
map("v", "w", "w")
map("v", "$", "$")
map("v", "d", "d")
map("v", "p", "p_")
map("v", "P", "P_")
map("v", "%", "%")
