require("lorem").setup({
	paragraph_length = 50, -- Default paragraph length in words
	formatter_enabled = true, -- Enable/disable text formatting
	complete_mappings = { "<Tab>", "<CR>" }, -- Key mappings for completing lorem commands
	default_lorem_length = 5, -- Default number of words for "loremX"
	line_width = 80, -- Maximum line width for formatted text
	lorem_text = [[             
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque tempus vel nisl eget facilisis. Phasellus consectetur bibendum nulla. Vivamus euismod id orci dictum facilisis. Ut eget nisi at orci rhoncus mollis. Aenean pulvinar massa a luctus molestie. Donec tortor libero, pharetra ut urna sit amet, iaculis dignissim sem. Duis id elit id dolor volutpat vulputate. Cras consectetur maximus rutrum. In ut semper tellus. Etiam nunc augue, cursus non scelerisque in, pulvinar quis elit. Curabitur ultricies, orci non eleifend viverra, eros est accumsan sapien, in accumsan lacus nibh sit amet felis. Ut eros dui, aliquam posuere lacinia pretium, ultricies ac diam. Praesent vehicula dignissim dolor. Nullam eu metus dapibus, consectetur arcu quis, faucibus est. Sed eu purus sodales, volutpat turpis efficitur, dignissim dui. In rhoncus est cursus efficitur dapibus. Curabitur hendrerit, est at aliquam accumsan, dui lacus ornare mauris, dictum mattis tellus libero eu nulla. Cras varius commodo nisl, in pulvinar urna fermentum id. Vivamus venenatis ac sem non porta. Nam a aliquet turpis, molestie semper tortor. Fusce non molestie lorem, sed facilisis sapien. Sed ut ipsum vitae justo gravida pretium nec ut enim. Phasellus ex nibh, vehicula sed odio sit amet, porta rutrum orci.
    Vivamus sed mi interdum, viverra quam sit amet, varius augue. Fusce a metus quam. Nulla auctor odio interdum nisi ultricies laoreet. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Mauris eu aliquam dui, quis vehicula justo. Sed vel luctus eros. Curabitur lobortis, nisi eget varius auctor, turpis nisl egestas urna, eu feugiat enim nibh ut augue. Curabitur quis leo arcu. Nam semper felis et velit molestie ornare. Aenean euismod, nulla et mattis ultricies, justo nisi vulputate ex, eu auctor lacus sem sed enim. Fusce id mauris at urna viverra iaculis. Integer vel enim scelerisque, scelerisque magna non, hendrerit diam. Maecenas metus nulla, cursus vel imperdiet at, laoreet et tellus. Sed nibh augue, tincidunt vel felis vel, mattis porta sem. Praesent vitae neque in nisi feugiat semper sit amet a dolor.
    Suspendisse eu justo nisi. Fusce tristique, tortor non sollicitudin consectetur, orci erat vestibulum justo, et volutpat purus mauris a dolor. Aenean venenatis egestas lacus, et egestas velit. Nulla sed elementum sem, vel egestas libero. Aenean tempor libero mi, at auctor ex blandit in. Curabitur ac iaculis mauris, fringilla tristique neque. Integer a fermentum nisl. Proin eu nulla pellentesque, volutpat neque sit amet, consequat augue.
    Nullam consequat mi id condimentum elementum. Suspendisse pharetra enim quis nibh fermentum volutpat. Suspendisse congue semper nulla ac tincidunt. Quisque euismod commodo vulputate. In hac habitasse platea dictumst. In tristique lacinia tellus vitae elementum. Sed ligula libero, maximus sit amet ante a, accumsan suscipit tellus. Suspendisse et condimentum dui. Nunc tempus diam a sem blandit, ut mattis enim ornare. Fusce a augue pharetra, faucibus nisl et, venenatis ipsum. Vestibulum elementum, dui sed accumsan rhoncus, felis urna posuere lorem, eu maximus ante velit id odio. Vivamus vulputate sollicitudin nibh in gravida. Cras ut pulvinar nunc. Nulla eget luctus ante, non tristique ipsum. Donec eget posuere.
  ]], -- Custom lorem ipsum text
})
