----------------------------------------------------------------
--catppuccin
require("core.lazyplug.colorscheme.catppuccin")
--
--gruvbox
-- require("core.lazyplug.colorscheme.gruvbox")
--
--tokyonight
-- require("core.lazyplug.colorscheme.tokyonight")
--
--kanagata
-- require("core.lazyplug.colorscheme.kanagata")
--
--vscode
-- require("core.lazyplug.colorscheme.vscode")
--
--everforest
-- require("core.lazyplug.colorscheme.everforest")
--
--dracula
-- require("core.lazyplug.colorscheme.dracula")
--
-- vim.o.background = "light"
----------------------------------------------------------------
-- visual multi settings theme corsor
